---
kind: pipeline
name: durl
steps:
- name: list files
  image: plugins/git
  commands:
  - git ls-files > list.txt
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
  - cat list.txt | durl check
---
kind: pipeline
name: shell scripts
clone:
  depth: 1
steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine:v0.7.0
  commands:
  - apk add git
  - sh scripts/shellcheck.sh
- name: shfmt
  image: mvdan/shfmt:v3.0.0
  commands:
  - 'shfmt -d .'
---
kind: pipeline
name: yamllint
steps:
- name: yamllint
  image: quay.io/suzuki_shunsuke/yamllint:1.20.0__1
  commands:
  - apk add git
  - sh scripts/yamllint.sh
---
kind: pipeline
name: build
volumes:
- name: gopath
  temp: {}
steps:
- name: download go modules
  image: &image_go golang:1.13.6
  commands:
  - go mod download
  volumes: &volumes
  - name: gopath
    path: /go
  environment:
    GOPATH: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.22.2-alpine
  commands:
  - golangci-lint run
  volumes: *volumes
  environment:
    GOPATH: /go
- name: codecov
  image: *image_go
  commands:
  # bash and cgo seem to be required
  - bash scripts/codecov_test.sh
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - test "$LOCAL" = "true" -o "$DRONE_BUILD_EVENT" = "pull_request" || bash /tmp/codecov.sh
  volumes: *volumes
  environment:
    GOPATH: /go
    CODECOV_TOKEN:
      from_secret: codecov_token
